-- ============================================
-- STUDENTS_SEED.SQL
-- ============================================
-- 38 Licenciadas Body Harmony
-- Senha padrão será configurada via setup_auto.php
-- ============================================

INSERT INTO `students` VALUES 
('1', 'Simône Àssis', 'simonesantosmassage', 'Bélgica', 'Bruxelas', '/uploads/photos/@simonesantosmassage.png', '32466081880', '@simonesantosmassage', NULL, '0', 'https://imgur.com/zYigNLn', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP),
('2', 'Kaprice Meirelles', 'kaprice_meirelles', 'SC/SP', 'Balneário Camboriú / Franca', '/uploads/photos/@kaprice_meirelles.png', '5521965595679', '@kaprice_meirelles', NULL, '0', 'https://imgur.com/tb1CZYE', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP),
('3', 'Julia Justo', 'a.fabrica.de.musas', 'SC', 'Balneário Camboriú', '/uploads/photos/@a.fabrica.de.musas.png', '5547997404540', '@a.fabrica.de.musas', NULL, '0', '', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP),
('4', 'Luciane Rezende', 'esteticalurezende', 'SP', 'Paraguaçu Paulista', '/uploads/photos/@esteticalurezende.png', '5518996936080', '@esteticalurezende', NULL, '0', '', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP),
('5', 'Sara Ribeiro', 'life.space.estetica', 'SP', 'Araraquara', '/uploads/photos/@life.space.estetica.png', '5511988881005', '@life.space.estetica', NULL, '0', '', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP),
('6', 'Gabriella Ribeiro', 'gabriellaribeiroestetica', 'PA', 'Parauapebas', '/uploads/photos/@gabriellaribeiroestetica.png', '5594981382888', '@gabriellaribeiroestetica', NULL, '0', '', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP),
('7', 'Juliana Gomes', 'fisioterapiadiasgomes', 'SP', 'São Paulo - Bairro do Limão', '/uploads/photos/@fisioterapiadiasgomes.png', '5511961488377', '@fisioterapiadiasgomes', NULL, '0', '', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP),
('8', 'Dayane Guillen', 'daianeguillen', 'PR', 'Umuarama', '/uploads/photos/@daianeguillen.png', '554499983

3222', '@daianeguillen', NULL, '0', '', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP),
('9', 'Paula Cristina Feliciano', 'esteticapaulafeliciano', 'SP', 'São Paulo - Parque Mandaqui', '/uploads/photos/@esteticapaulafeliciano.png', '5511968702913', '@esteticapaulafeliciano', NULL, '0', '', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP),
('10', 'Lusilene Leite', 'lusilene_leite', 'RS', 'Palmitinho', '/uploads/photos/@lusilene_leite.png', NULL, '@lusilene_leite', NULL, '0', '', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP),
('11', 'Michele Penteado', 'michelepenteado_estetica', 'SP', 'Araraquara', '/uploads/photos/@michelepenteado.png', '5516981218128', 'michelepenteado_estetica', NULL, '0', '', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP),
('12', 'Marina Gersony', 'marinagersonystudio', 'MG', 'Arcos', '/uploads/photos/@marinagersonystudio.png', '553798094212', '@marinagersonystudio', NULL, '0', '', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP),
('13', 'Viviane Baptistella', 'clinicamentallizeamericana', 'SP', 'Americana', '/uploads/photos/@clinicamentallizeamericana.png', '5519993559039', '@clinicamentallizeamericana', NULL, '0', '', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP),
('14', 'Katyuscia Saturnino', 'katyusciasaturnino', 'GO', 'Jatai', '/uploads/photos/@katyusciasaturnino.png', '5564999087014', '@katyusciasaturnino', NULL, '0', '', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP),
('15', 'Luciana Rubo', 'bellaluestetica', 'MS', 'Ribas do Rio Pardo', '/uploads/photos/@bellaluestetica.png', '5567991779646', '@bellaluestetica', NULL, '0', '', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP),
('16', 'Perla Cristina', 'perlacristinaesteticista', 'GO', 'Goiatuba', '/uploads/photos/@perlacristinaesteticista.png', '556484499204', '@perlacristinaesteticista', NULL, '0', '', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP),
('17', 'Ivana Giacon', 'ivanargiacon', 'SP', 'Quatá', '/uploads/photos/@ivanargiacon.png', '5518997641649', '@ivanargiacon', NULL, '0', '', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP),
('18', 'Bruna Gimenes', 'biocore360_oficial', 'SP', 'Jundiaí', '/uploads/photos/@bruna.gimeness_estetica.png', '5511940583622', '@biocore360_oficial', NULL, '0', '', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP),
('19', 'Isabella Mazzari Alvares', 'isabellamazzari.fisio', 'PR', 'Ponta Grossa', '/uploads/photos/@isabellamazzari.fisio.png', '5542999121730', '@isabellamazzari.fisio', NULL, '0', '', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP),
('20', 'Rejane Souto', 'rejanesouto_', 'BA', 'Vitória da Conquista', '/uploads/photos/@rejanesouto_.png', '5577999934781', '@rejanesouto_', NULL, '0', '', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP),
('21', 'Daniella Garcia', 'esteticadanigarcia', 'SP', 'São Paulo', '/uploads/photos/@esteticadanigarcia.png', '5511956575789', '@esteticadanigarcia', NULL, '0', '', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP),
('22', 'Hávylla Vitória', 'havyllavitoria.fisio', 'GO', 'Inhumas', '/uploads/photos/@havyllavitoria.fisio.png', '5562992536256', '@havyllavitoria.fisio', NULL, '0', '', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP),
('23', 'Paola Antunes', 'clinicapaolaantunes', 'RJ', 'Rio de Janeiro', '/uploads/photos/@clinicapaolaantunes.png', '5521987839057', '@clinicapaolaantunes', NULL, '0', '', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP),
('24', 'Ana Bica', 'biqueclinic', 'Uruguai', 'Montevideo', '/uploads/photos/@biqueclinic.png', NULL, '@biqueclinic', NULL, '0', '', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP),
('25', 'Rubiana Reusing', 'rubianareusing', 'PR', 'Joaquim Távora', '/uploads/photos/@rubianareusing.png', '5543996627669', '@rubianareusing', NULL, '0', '', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP),
('26', 'Gabriela Gasque', 'bodyharmony.marilia', 'SP', 'Marília', '/uploads/photos/@gabigasque.png', '5511988881026', '@bodyharmony.marilia', NULL, '0', '', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP),
('27', 'Joice Burrego', 'joiceburrego', 'SP', 'São Paulo - Itaquera / Anália Franco', '/uploads/photos/@joiceburrego.png', '5511942001064', '@joiceburrego', NULL, '0', '', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP),
('28', 'Michelle Salvador', 'fisiomichellesalvador', 'MG', 'Juiz de Fora', '/uploads/photos/@fisiomichellesalvador.png', '5532988747176', '@fisiomichellesalvador', NULL, '0', '', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP),
('29', 'Fabiana Medina', 'fabianamedinaestetica', 'SP', 'Santos', '/uploads/photos/@fabianamedinaestetica.png', '5513991530429', '@fabianamedinaestetica', NULL, '0', '', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP),
('30', 'Luana Reis', 'luanareisoficial', 'SP', 'São Paulo', '/uploads/photos/@luanareisoficial.png', NULL, '@luanareisoficial', NULL, '0', '', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP),
('31', 'Lilian Motta', 'esteticalilianmotta', 'ES', 'Venda Nova do Imigrante', '/uploads/photos/@esteticalilianmotta.png', '5527998440802', '@esteticalilianmotta', NULL, '0', '', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP),
('32', 'Nanda Raggon', 'nandaraggon', 'SP', 'São Paulo - Anália Franco', '/uploads/photos/@nandaraggon.png', '5511980178886', '@nandaraggon', NULL, '0', '', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP),
('33', 'Leticia Caetano', 'leh.caetano_', 'SP', 'São Bernardo do Campo', '/uploads/photos/@leh.caetano_.png', '5511974400881', '@leh.caetano_', NULL, '0', '', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP),
('34', 'Sirlene Coutinho Souza', 'siu_coutinho_esthetique', 'Bélgica', 'Gent', '/uploads/photos/@siu_coutinho_esthetique.png', '32490542746', '@siu_coutinho_esthetique', NULL, '0', '', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP),
('35', 'Elisangela Martins', 'uniquestar____', 'SP', 'São Paulo - Mooca (Zona Leste)', '/uploads/photos/@uniquestar____.png', '5511952116346', '@uniquestar____', NULL, '0', '', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP),
('36', 'Adriana Fernandez', 'Adrianalfernandez', 'SP', 'São Paulo - Morumbi', '/uploads/photos/@Adrianalfernandez.png', NULL, '@Adrianalfernandez', NULL, '0', '', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP),
('37', 'Thamyres Menezes', 'clinicalecorp_', 'SP', 'Barueri', '/uploads/photos/@clinicalecorp_.png', '5511994936435', '@clinicalecorp_', NULL, '0', '', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP),
('38', 'Joselene Silva', 'josisilva_estetica', 'SP', 'Assis', '/uploads/photos/@josisilva_estetica.png', '5511988881038', '@josisilva_estetica', NULL, '0', '', '["/gallery/result.png", "/gallery/treatment.png"]', '0', '1', '1', NULL, CURRENT_TIMESTAMP);
