-- ==========================================
-- SEEDS: LICENCIADAS BODY HARMONY (v2.0)
-- ==========================================
-- Generated from: openspec/assets/design-system/manual/Licenciadas-dataset.md
-- Target Table: students (mapped from 'licenciadas')
-- Password Hash: $2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn (Mudar123!)
-- ==========================================

INSERT INTO
    `students` (
        `name`,
        `username`,
        `state`,
        `location`,
        `whatsapp`,
        `instagram`,
        `email`,
        `password_hash`,
        `is_active`,
        `photo_url`
    )
VALUES (
        'Simône Àssis',
        'simonesantosmassage',
        'Bélgica',
        'Bruxelas',
        '32466081880',
        '@simonesantosmassage',
        'simone.assis@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@simonesantosmassage.png'
    ),
    (
        'Kaprice Meirelles',
        'kaprice_meirelles',
        'SC/SP',
        'Balneário Camboriú / Franca',
        '5521965595679',
        '@kaprice_meirelles',
        'kaprice.meirelles@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@kaprice_meirelles.png'
    ),
    (
        'Julia Justo',
        'a.fabrica.de.musas',
        'SC',
        'Balneário Camboriú',
        '5547997404540',
        '@a.fabrica.de.musas',
        'julia.justo@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@a.fabrica.de.musas.png'
    ),
    (
        'Luciane Rezende',
        'esteticalurezende',
        'SP',
        'Paraguaçu Paulista',
        '5518996936080',
        '@esteticalurezende',
        'luciane.rezende@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@esteticalurezende.png'
    ),
    (
        'Sara Ribeiro',
        'life.space.estetica',
        'SP',
        'Araraquara',
        '5511988881005',
        '@life.space.estetica',
        'sara.ribeiro@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@life.space.estetica.png'
    ),
    (
        'Gabriella Ribeiro',
        'gabriellaribeiroestetica',
        'PA',
        'Parauapebas',
        '5594981382888',
        '@gabriellaribeiroestetica',
        'gabriella.ribeiro@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@gabriellaribeiroestetica.png'
    ),
    (
        'Juliana Gomes',
        'fisioterapiadiasgomes',
        'SP',
        'São Paulo - Bairro do Limão',
        '5511961488377',
        '@fisioterapiadiasgomes',
        'juliana.gomes@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@fisioterapiadiasgomes.png'
    ),
    (
        'Dayane Guillen',
        'daianeguillen',
        'PR',
        'Umuarama',
        '5544999833222',
        '@daianeguillen',
        'dayane.guillen@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@daianeguillen.png'
    ),
    (
        'Paula Cristina Feliciano',
        'esteticapaulafeliciano',
        'SP',
        'São Paulo - Parque Mandaqui',
        '5511968702913',
        '@esteticapaulafeliciano',
        'paula.feliciano@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@esteticapaulafeliciano.png'
    ),
    (
        'Lusilene Leite',
        'lusilene_leite',
        'RS',
        'Palmitinho',
        NULL,
        '@lusilene_leite',
        'lusilene.leite@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@lusilene_leite.png'
    ),
    (
        'Michele Penteado',
        'michelepenteado_estetica',
        'SP',
        'Araraquara',
        '5516981218128',
        '@michelepenteado_estetica',
        'michele.penteado@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@michelepenteado_estetica.png'
    ),
    (
        'Marina Gersony',
        'marinagersonystudio',
        'MG',
        'Arcos',
        '553798094212',
        '@marinagersonystudio',
        'marina.gersony@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@marinagersonystudio.png'
    ),
    (
        'Viviane Baptistella',
        'clinicamentallizeamericana',
        'SP',
        'Americana',
        '5519993559039',
        '@clinicamentallizeamericana',
        'viviane.baptistella@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@clinicamentallizeamericana.png'
    ),
    (
        'Katyuscia Saturnino',
        'katyusciasaturnino',
        'GO',
        'Jatai',
        '5564999087014',
        '@katyusciasaturnino',
        'katyuscia.saturnino@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@katyusciasaturnino.png'
    ),
    (
        'Luciana Rubo',
        'bellaluestetica',
        'MS',
        'Ribas do Rio Pardo',
        '5567991779646',
        '@bellaluestetica',
        'luciana.rubo@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@bellaluestetica.png'
    ),
    (
        'Perla Cristina',
        'perlacristinaesteticista',
        'GO',
        'Goiatuba',
        '556484499204',
        '@perlacristinaesteticista',
        'perla.cristina@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@perlacristinaesteticista.png'
    ),
    (
        'Ivana Giacon',
        'ivanargiacon',
        'SP',
        'Quatá',
        '5518997641649',
        '@ivanargiacon',
        'ivana.giacon@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@ivanargiacon.png'
    ),
    (
        'Bruna Gimenes',
        'biocore360_oficial',
        'SP',
        'Jundiaí',
        '5511940583622',
        '@biocore360_oficial',
        'bruna.gimenes@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@biocore360_oficial.png'
    ),
    (
        'Isabella Mazzari Alvares',
        'isabellamazzari.fisio',
        'PR',
        'Ponta Grossa',
        '5542999121730',
        '@isabellamazzari.fisio',
        'isabella.alvares@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@isabellamazzari.fisio.png'
    ),
    (
        'Rejane Souto',
        'rejanesouto_',
        'BA',
        'Vitória da Conquista',
        '5577999934781',
        '@rejanesouto_',
        'rejane.souto@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@rejanesouto_.png'
    ),
    (
        'Daniella Garcia',
        'esteticadanigarcia',
        'SP',
        'São Paulo',
        '5511956575789',
        '@esteticadanigarcia',
        'daniella.garcia@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@esteticadanigarcia.png'
    ),
    (
        'Hávylla Vitória',
        'havyllavitoria.fisio',
        'GO',
        'Inhumas',
        '5562992536256',
        '@havyllavitoria.fisio',
        'havylla.vitoria@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@havyllavitoria.fisio.png'
    ),
    (
        'Paola Antunes',
        'clinicapaolaantunes',
        'RJ',
        'Rio de Janeiro',
        '5521987839057',
        '@clinicapaolaantunes',
        'paola.antunes@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@clinicapaolaantunes.png'
    ),
    (
        'Ana Bica',
        'biqueclinic',
        'Uruguai',
        'Montevideo',
        NULL,
        '@biqueclinic',
        'ana.bica@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@biqueclinic.png'
    ),
    (
        'Rubiana Reusing',
        'rubianareusing',
        'PR',
        'Joaquim Távora',
        '5543996627669',
        '@rubianareusing',
        'rubiana.reusing@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@rubianareusing.png'
    ),
    (
        'Gabriela Gasque',
        'bodyharmony.marilia',
        'SP',
        'Marília',
        '5511988881026',
        '@bodyharmony.marilia',
        'gabriela.gasque@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@bodyharmony.marilia.png'
    ),
    (
        'Joice Burrego',
        'joiceburrego',
        'SP',
        'São Paulo - Itaquera / Anália Franco',
        '5511942001064',
        '@joiceburrego',
        'joice.burrego@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@joiceburrego.png'
    ),
    (
        'Michelle Salvador',
        'fisiomichellesalvador',
        'MG',
        'Juiz de Fora',
        '5532988747176',
        '@fisiomichellesalvador',
        'michelle.salvador@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@fisiomichellesalvador.png'
    ),
    (
        'Fabiana Medina',
        'fabianamedinaestetica',
        'SP',
        'Santos',
        '5513991530429',
        '@fabianamedinaestetica',
        'fabiana.medina@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@fabianamedinaestetica.png'
    ),
    (
        'Luana Reis',
        'luanareisoficial',
        'SP',
        'São Paulo',
        NULL,
        '@luanareisoficial',
        'luana.reis@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@luanareisoficial.png'
    ),
    (
        'Lilian Motta',
        'esteticalilianmotta',
        'ES',
        'Venda Nova do Imigrante',
        '5527998440802',
        '@esteticalilianmotta',
        'lilian.motta@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@esteticalilianmotta.png'
    ),
    (
        'Nanda Raggon',
        'nandaraggon',
        'SP',
        'São Paulo - Anália Franco',
        '5511980178886',
        '@nandaraggon',
        'nanda.raggon@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@nandaraggon.png'
    ),
    (
        'Leticia Caetano',
        'leh.caetano_',
        'SP',
        'São Bernardo do Campo',
        '5511974400881',
        '@leh.caetano_',
        'leticia.caetano@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@leh.caetano_.png'
    ),
    (
        'Sirlene Coutinho Souza',
        'siu_coutinho_esthetique',
        'Bélgica',
        'Gent',
        '32490542746',
        '@siu_coutinho_esthetique',
        'sirlene.souza@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@siu_coutinho_esthetique.png'
    ),
    (
        'Elisangela Martins',
        'uniquestar____',
        'SP',
        'São Paulo - Mooca (Zona Leste)',
        '5511952116346',
        '@uniquestar____',
        'elisangela.martins@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@uniquestar____.png'
    ),
    (
        'Adriana Fernandez',
        'adriana.fernandez',
        'SP',
        'São Paulo - Morumbi',
        NULL,
        NULL,
        'adriana.fernandez@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@adriana.fernandez.png'
    ),
    (
        'Thamyres Menezes',
        'clinicalecorp_',
        'SP',
        'Barueri',
        '5511994936435',
        '@clinicalecorp_',
        'thamyres.menezes@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@clinicalecorp_.png'
    ),
    (
        'Joselene Silva',
        'josisilva_estetica',
        'SP',
        'Assis',
        '5511988881038',
        '@josisilva_estetica',
        'joselene.silva@bodyharmony.com',
        '$2y$12$IHPBXgfV5LZ/Re2ZPXXXgOzaG45WFFkCCd647agbxti7Apfx3eAGn',
        1,
        '/uploads/photos/@josisilva_estetica.png'
    )
ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    state = VALUES(state),
    location = VALUES(location),
    whatsapp = VALUES(whatsapp),
    email = VALUES(email),
    password_hash = VALUES(password_hash),
    is_active = VALUES(is_active),
    photo_url = VALUES(photo_url);