-- SAFE IMPORT WRAPPER
-- Use this template when importing data to Hostinger to prevent FK errors

SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS;

SET FOREIGN_KEY_CHECKS = 0;

SET @OLD_SQL_MODE = @@SQL_MODE;

SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';

-- TRANSACTION START
START TRANSACTION;

-- [PASTE YOUR EXPORTED DATA HERE]
-- ...
-- ...

COMMIT;

-- RESTORE SETTINGS
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;

SET SQL_MODE = @OLD_SQL_MODE;